# AttributeError-NoneType-object-has-no-attribute-response-mitmproxy-has-crashed-
MobaXterm X11 proxy: Unsupported authorisation protocol /usr/lib/python2.7/dist-packages/gtk-2.0/gtk/__init__.py:57: GtkWarning: could not open display   warnings.warn(str(e), _gtk.Warning) Traceback (most recent call last):   File "/usr/local/lib/python2.7/dist-packages/libmproxy/proxy/server.py", line 120, in handle     root_layer()   File "/usr/local/lib/python2.7/dist-packages/libmproxy/proxy/modes/transparent_proxy.py", line 21, in __call__     layer()   File "/usr/local/lib/python2.7/dist-packages/libmproxy/protocol/tls.py", line 272, in __call__     layer()   File "/usr/local/lib/python2.7/dist-packages/libmproxy/protocol/http.py", line 130, in __call__     layer()   File "/usr/local/lib/python2.7/dist-packages/libmproxy/protocol/http.py", line 340, in __call__     self.get_response_from_server(flow)   File "/usr/local/lib/python2.7/dist-packages/libmproxy/protocol/http.py", line 471, in get_response_from_server     if flow.response.stream: AttributeError: 'NoneType' object has no attribute 'response'  mitmproxy has crashed! Please lodge a bug report at: https://github.com/mitmproxy/mitmproxy
